## Imports

In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# np array main dataype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [5]:
# 2-dimension array
a2 = np.array([[1,2,3],[4,5,6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# 3-dimension array
a3 = np.array([
                [[1,2,3],
                 [4,5,6], 
                 [7,8,9]],
    
                [[10,11,12],
                 [13,14,15],
                 [16,17,18]]
               ])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a3[0][0][0]

1

In [9]:
a3[1][0][0]

10

In [10]:
a1.shape

(3,)

In [11]:
a2.shape

(2, 3)

In [12]:
a3.shape

(2, 3, 3)

In [14]:
# Create a DF from a NumPy array
import pandas as pd
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

# Creating arrays


In [15]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [16]:
sample_array.dtype

dtype('int32')

In [19]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
range_array = np.arange(0.1,10.1,2,"float64").round(2)
range_array

array([0.1, 2.1, 4.1, 6.1, 8.1])

In [31]:
range_array.dtype

dtype('float64')

In [37]:
random_array = np.random.randint(1, 10, size = (3,5))
random_array

array([[8, 3, 6, 2, 6],
       [5, 9, 2, 6, 3],
       [6, 6, 8, 3, 1]])

In [39]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.7137366 , 0.87936797, 0.19099315],
       [0.5092647 , 0.31300874, 0.07940604],
       [0.3008296 , 0.08174068, 0.99018677],
       [0.25163855, 0.18718866, 0.91893423],
       [0.31584336, 0.45920875, 0.67378281]])

# Viewing arrays and matrices

In [42]:
np.unique(random_array)

array([1, 2, 3, 5, 6, 8, 9])

In [43]:
a1[0]

1

In [44]:
a2[0]

array([1, 2, 3])

In [60]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

# Manipulation & comparing arrays

## Arithmetic

In [62]:
a1

array([1, 2, 3])

In [65]:
ones = np.ones(3).astype(a1[0])
ones

array([1, 1, 1])

In [66]:
a1 + ones

array([2, 3, 4])

In [67]:
a1 - ones

array([0, 1, 2])

In [68]:
a1 * ones

array([1, 2, 3])

In [69]:
a1 * a2

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [70]:
a2 * a1

array([[ 1,  4,  9],
       [ 4, 10, 18]])

In [71]:
a2

array([[1, 2, 3],
       [4, 5, 6]])