In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2, 3],[4, 5, 6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([
                [[1,2,3],
                 [4,5,6],
                 [7,8,9]],
                [[10,11,12],
                 [13,14,15],
                 [16,17,18]]
              ]) 
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [12]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
print("a1 shape: ", a1.shape)
print("a1 datatype: ", a1.dtype)
print("a1 size: ", a1.size)
print("a1 type", type(a1))

a1 shape:  (3,)
a1 datatype:  int32
a1 size:  3
a1 type <class 'numpy.ndarray'>


In [13]:
# Attributes of 2-dimensional array
print("a2 shape: ", a2.shape)
print("a2 datatype: ", a2.dtype)
print("a2 size: ", a2.size)
print("a2 type", type(a2))

a2 shape:  (2, 3)
a2 datatype:  int32
a2 size:  6
a2 type <class 'numpy.ndarray'>


In [14]:
# Attributes of 3-dimensional array
print("a3 shape: ", a3.shape)
print("a3 datatype: ", a3.dtype)
print("a3 size: ", a3.size)
print("a3 type", type(a3))

a3 shape:  (2, 3, 3)
a3 datatype:  int32
a3 size:  18
a3 type <class 'numpy.ndarray'>


In [23]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
a1_df = pd.DataFrame(a1).T
a1_df

0  1  2
0  1  2  3

In [25]:
# Create an array of shape (10, 2) with only ones
ones = np.ones(shape = (10,2), dtype = "int32")
ones

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [26]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros(shape = (7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [28]:
# Create an array within a range of 0 and 100 with step 3
arr_1 = np.arange(0, 100, 3)
arr_1

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [30]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr_2 = np.random.randint(0,10, size = (7,2))
arr_2

array([[2, 1],
       [7, 1],
       [0, 8],
       [1, 6],
       [1, 9],
       [2, 5],
       [3, 3]])

In [32]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr_3 = np.random.random(size = (3,5))
arr_3

array([[0.75351581, 0.44674142, 0.04536921, 0.55025624, 0.36613848],
       [0.77777654, 0.70864605, 0.15954061, 0.88487777, 0.47840404],
       [0.27974155, 0.58430208, 0.41913909, 0.28665977, 0.2535652 ]])

In [35]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
arr_4 = np.random.randint(0, 10, size = (4,6))
arr_4

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [36]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arr_4 = np.random.randint(1, 11, size = (3,7))

# Find the unique numbers in the array you just created
np.unique(arr_4)

array([ 1,  2,  3,  4,  5,  7,  9, 10])

In [38]:
# Find the 0'th index of the latest array you created
arr_4[0][0]

9

In [40]:
arr_4

array([[ 9,  1, 10,  3,  7,  4,  9],
       [ 3,  5,  3,  7,  5,  9,  7],
       [ 2,  4,  9,  2, 10,  9, 10]])

In [41]:
# Get the first 2 rows of latest array you created
arr_4[:2]

array([[ 9,  1, 10,  3,  7,  4,  9],
       [ 3,  5,  3,  7,  5,  9,  7]])

In [42]:
# Get the first 2 values of the first 2 rows of the latest array
arr_4[:2,:2]

array([[9, 1],
       [3, 5]])

In [44]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
arr_rand_1 = np.random.randint(0,11, size = (3, 5))
ones = np.ones(shape = (3, 5))

In [45]:
# Add the two arrays together
arr_rand_1 + ones

array([[ 4.,  6.,  2., 10.,  2.],
       [10.,  4.,  8.,  7.,  9.],
       [ 8.,  5.,  2.,  5.,  8.]])

In [46]:
# Create another array of ones of shape (5, 3)
ones_2 = np.ones(shape = (5,3))

In [47]:
# Try add the array of ones and the other most recent array together
arr_rand_1 + ones_2

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [48]:
## This arrays cant be added together beacause of shape (or size) problems